spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: ${SPRING_DATA_MONGODB_DATABASE}  # buy-one
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}  # kafka:9092

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL-DEFAULTZONE}  # discovery-service:8761

logging:
  level:
    org.springframework.security: WARN
